[profile.default]
test = 'test'
solc_version = '0.8.17'
optimizer = true
optimizer_runs = 1000000
src = 'src'
out = 'out'
libs = ['lib']
remappings = [ 'forge-std/=lib/forge-std/src/', 'OpenZeppelin/openzeppelin-contracts@4.7.3/=lib/openzeppelin-contracts/', 'OpenZeppelin/openzeppelin-contracts-upgradeable@4.7.3/=lib/openzeppelin-contracts-upgradeable/'] 